### ISSUE TITLE
duplicate symbols / gcc-12

### ISSUE THREAD

**Issue by 21tesla** [outpace-bio/DAlphaBall#3]
I am trying to compile DAlphaBall on a **MacM1 with homebrew** (gcc-12/gfortran-12) and there seems to be issues between the compilers with the dreaded underscores

> duplicate symbol '_dtest' in:
>     sos_minor_gmp.o
>     alf_tools_gmp.o

Any idea how to fix this? 

In **binding.c**, should 

> 	extern void **F77Name2**(cavballs)( double *x, double *y, double *z, double *r, int *ncav );

be 

> 	extern void **F77Name1**(cavballs)( double *x, double *y, double *z, double *r, int *ncav );

thank you !

**Comment by weitzner** [comment]
This codebase is pretty old - I would recommend using an older compile or building via conda to get it going
